# Generated by Django 5.1.1 on 2024-10-10 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CbtIndustry',
            fields=[
                ('PR_INDUSTRY_ID', models.AutoField(primary_key=True, serialize=False)),
                ('PR_NAME', models.CharField(blank=True, max_length=255, null=True)),
                ('PR_SLUG', models.SlugField(blank=True, max_length=255, unique=True)),
                ('PR_DESCRIPTION', models.TextField(blank=True, null=True)),
                ('PR_BANNER_IMAGE', models.CharField(blank=True, max_length=255, null=True)),
                ('PR_STATUS', models.IntegerField(blank=True, default=0, null=True)),
                ('PR_CREATED_AT', models.DateTimeField(auto_now_add=True)),
                ('PR_MODIFIED_AT', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'cbt_industry',
            },
        ),
        migrations.CreateModel(
            name='CbtPricing',
            fields=[
                ('PR_PRODUCT_ID', models.AutoField(primary_key=True, serialize=False)),
                ('PR_NAME', models.CharField(blank=True, max_length=255, null=True)),
                ('PR_SLUG', models.SlugField(blank=True, max_length=255, unique=True)),
                ('PR_DESCRIPTION', models.TextField(blank=True, null=True)),
                ('PR_BANNER_IMAGE', models.CharField(blank=True, max_length=255, null=True)),
                ('PR_STATUS', models.IntegerField(blank=True, default=0, null=True)),
                ('PR_CREATED_AT', models.DateTimeField(auto_now_add=True)),
                ('PR_MODIFIED_AT', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'cbt_pricing',
            },
        ),
        migrations.CreateModel(
            name='CbtProduct',
            fields=[
                ('PR_PRODUCT_ID', models.AutoField(primary_key=True, serialize=False)),
                ('PR_NAME', models.CharField(blank=True, max_length=255, null=True)),
                ('PR_SLUG', models.SlugField(blank=True, max_length=255, unique=True)),
                ('PR_DESCRIPTION', models.TextField(blank=True, null=True)),
                ('PR_BANNER_IMAGE', models.CharField(blank=True, max_length=255, null=True)),
                ('PR_STATUS', models.IntegerField(blank=True, default=0, null=True)),
                ('PR_CREATED_AT', models.DateTimeField(auto_now_add=True)),
                ('PR_MODIFIED_AT', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'cbt_product',
            },
        ),
    ]
