# Generated by Django 5.1.1 on 2024-10-11 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websiteApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cbtindustry',
            name='PR_CONTENT_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cbtpricing',
            name='PR_CONTENT_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cbtproduct',
            name='PR_CONTENT_1',
            field=models.TextField(blank=True, null=True),
        ),
    ]
