# Generated by Django 5.1.1 on 2024-10-11 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('websiteApp', '0002_cbtindustry_pr_content_1_cbtpricing_pr_content_1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cbtpricing',
            old_name='PR_PRODUCT_ID',
            new_name='PR_PRICING_ID',
        ),
    ]
