# Generated by Django 5.1.1 on 2024-10-11 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websiteApp', '0003_rename_pr_product_id_cbtpricing_pr_pricing_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CbtPricingPlan',
            fields=[
                ('PR_PLAN_ID', models.AutoField(primary_key=True, serialize=False)),
                ('PR_NAME', models.CharField(max_length=255)),
                ('PR_PRICE', models.DecimalField(decimal_places=2, max_digits=10)),
                ('PR_FEATURES', models.TextField(blank=True, null=True)),
                ('PR_STATUS', models.IntegerField(default=1)),
                ('PR_CREATED_AT', models.DateTimeField(auto_now_add=True)),
                ('PR_MODIFIED_AT', models.DateTimeField(auto_now=True)),
                ('PR_PRICING', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='websiteApp.cbtpricing')),
            ],
            options={
                'db_table': 'cbt_pricing_plan',
            },
        ),
    ]
