# Generated by Django 5.1.1 on 2024-10-14 05:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websiteApp', '0004_cbtpricingplan'),
    ]

    operations = [
        migrations.CreateModel(
            name='CbtWebsiteData',
            fields=[
                ('PR_WEBSITE_ID', models.AutoField(primary_key=True, serialize=False)),
                ('PR_NAME', models.CharField(max_length=255)),
                ('PR_LOGO', models.CharField(blank=True, default='/media/default-img.png', max_length=255, null=True)),
                ('PR_DESCRIPTION', models.TextField(blank=True, default='', null=True)),
                ('PR_STATUS', models.IntegerField(blank=True, default=0, null=True)),
                ('PR_CREATED_AT', models.DateTimeField(auto_now_add=True)),
                ('PR_MODIFIED_AT', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'cbt_website_data',
            },
        ),
        migrations.AddField(
            model_name='cbtindustry',
            name='PR_WEBSITE',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='websiteApp.cbtwebsitedata'),
        ),
    ]
