# Generated by Django 5.1.1 on 2024-10-14 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websiteApp', '0005_cbtwebsitedata_cbtindustry_pr_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='cbtpricing',
            name='PR_WEBSITE',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='websiteApp.cbtwebsitedata'),
        ),
        migrations.AddField(
            model_name='cbtproduct',
            name='PR_WEBSITE',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='websiteApp.cbtwebsitedata'),
        ),
    ]
